// Loader for the bundled Hisn al-Muslim collection (public/data/hisn.json),
// generated by scripts/generate-hisn.mjs and gated by npm run verify:data.
// Precached by the service worker, so it is fully available offline.

export interface HisnChapter {
  n: number
  title: string
  titleAr: string
}

export interface HisnDua {
  n: number
  /** chapter number */
  ch: number
  ar: string
  translit: string
  meaning: string
  ref: string
}

export interface HisnData {
  source: string
  chapters: HisnChapter[]
  duas: HisnDua[]
}

let cached: HisnData | null = null
let inflight: Promise<HisnData> | null = null

export function loadHisn(): Promise<HisnData> {
  if (cached) return Promise.resolve(cached)
  if (inflight) return inflight
  inflight = fetch(`${import.meta.env.BASE_URL}data/hisn.json`)
    .then((r) => {
      if (!r.ok) throw new Error(`hisn: HTTP ${r.status}`)
      return r.json() as Promise<HisnData>
    })
    .then((d) => {
      cached = d
      inflight = null
      return d
    })
    .catch((e) => {
      inflight = null
      throw e
    })
  return inflight
}

/** Case-insensitive match across title, Arabic, transliteration and meaning. */
export function filterHisn(data: HisnData, query: string) {
  const q = query.trim().toLowerCase()
  const chapterTitle = new Map(data.chapters.map((c) => [c.n, c.title.toLowerCase()]))
  const duas = q
    ? data.duas.filter((d) =>
        [d.ar, d.translit, d.meaning, d.ref, chapterTitle.get(d.ch) ?? ''].some((f) =>
          f.toLowerCase().includes(q),
        ),
      )
    : data.duas
  const chapterNumbers = new Set(duas.map((d) => d.ch))
  return { duas, chapters: data.chapters.filter((c) => chapterNumbers.has(c.n)) }
}
