// Loader for the bundled Qur'an text (public/quran/<n>.json), generated by
// scripts/generate-quran.mjs and gated by npm run verify:data.
// Fetched per surah and cached in memory; the service worker caches the
// files on disk, so a surah you have opened stays available offline.

export interface Ayah {
  /** ayah number within the surah */
  i: number
  /** Uthmani Arabic */
  ar: string
  /** English transliteration (Tanzil) */
  tr: string
  /** English translation (Saheeh International) */
  en: string
}

export interface SurahText {
  n: number
  name: string
  meaning: string
  ayahs: number
  startPage: number
  verses: Ayah[]
}

const cache = new Map<number, SurahText>()
const inflight = new Map<number, Promise<SurahText>>()

export function loadSurah(n: number): Promise<SurahText> {
  const cached = cache.get(n)
  if (cached) return Promise.resolve(cached)
  const pending = inflight.get(n)
  if (pending) return pending
  const p = fetch(`${import.meta.env.BASE_URL}quran/${n}.json`)
    .then((r) => {
      if (!r.ok) throw new Error(`surah ${n}: HTTP ${r.status}`)
      return r.json() as Promise<SurahText>
    })
    .then((s) => {
      // Small LRU: the service worker holds the files on disk, so memory only
      // needs the surahs in recent use — not all 114 parsed at once.
      if (cache.size >= 5) cache.delete(cache.keys().next().value as number)
      cache.set(n, s)
      inflight.delete(n)
      return s
    })
    .catch((e) => {
      inflight.delete(n)
      throw e
    })
  inflight.set(n, p)
  return p
}

/** EveryAyah per-ayah recitation URL (Al-Husary — the classic hifz reciter). */
export const ayahAudioUrl = (surah: number, ayah: number) =>
  `https://everyayah.com/data/Husary_128kbps/${String(surah).padStart(3, '0')}${String(ayah).padStart(3, '0')}.mp3`
